
CREATE TABLE vq_tbl_stock (
    id SERIAL PRIMARY KEY,
    "Stock_Name" TEXT,
    stock_symbol TEXT UNIQUE NOT NULL,
    "Ticker" TEXT,
    "Sector" TEXT,
    "Current_Financial_Year" TEXT,
    "Sector_PE" NUMERIC,
    "EPS_Growth_Rate" NUMERIC,
    "Intrinsic_PE" NUMERIC,
    "PE_Growth_Rate" NUMERIC,
    "PE_Best_Case" NUMERIC,
    "Intrinsic_PEG_Ratio" NUMERIC,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE vq_tbl_financial_statement (
    id SERIAL PRIMARY KEY,
    stock_symbol TEXT REFERENCES vq_tbl_stock(stock_symbol),
    "Date" DATE,
    "Tax Effect Of Unusual Items" NUMERIC,
    "Tax Rate For Calcs" NUMERIC,
    "Normalized EBITDA" NUMERIC,
    "Total Unusual Items" NUMERIC,
    "Total Unusual Items Excluding Goodwill" NUMERIC,
    "Net Income From Continuing Operation Net Minority Interest" NUMERIC,
    "Reconciled Depreciation" NUMERIC,
    "Reconciled Cost Of Revenue" NUMERIC,
    "EBITDA" NUMERIC,
    "EBIT" NUMERIC,
    "Net Interest Income" NUMERIC,
    "Interest Expense" NUMERIC,
    "Interest Income" NUMERIC,
    "Normalized Income" NUMERIC,
    "Net Income From Continuing And Discontinued Operation" NUMERIC,
    "Total Expenses" NUMERIC,
    "Rent Expense Supplemental" NUMERIC,
    "Diluted Average Shares" NUMERIC,
    "Basic Average Shares" NUMERIC,
    "Diluted EPS" NUMERIC,
    "Basic EPS" NUMERIC,
    "Diluted NI Availto Com Stockholders" NUMERIC,
    "Net Income Common Stockholders" NUMERIC,
    "Otherunder Preferred Stock Dividend" NUMERIC,
    "Net Income" NUMERIC,
    "Minority Interests" NUMERIC,
    "Net Income Including Noncontrolling Interests" NUMERIC,
    "Net Income Discontinuous Operations" NUMERIC,
    "Net Income Continuous Operations" NUMERIC,
    "Tax Provision" NUMERIC,
    "Pretax Income" NUMERIC,
    "Other Non Operating Income Expenses" NUMERIC,
    "Special Income Charges" NUMERIC,
    "Other Special Charges" NUMERIC,
    "Write Off" NUMERIC,
    "Impairment Of Capital Assets" NUMERIC,
    "Net Non Operating Interest Income Expense" NUMERIC,
    "Total Other Finance Cost" NUMERIC,
    "Interest Expense Non Operating" NUMERIC,
    "Interest Income Non Operating" NUMERIC,
    "Operating Income" NUMERIC,
    "Operating Expense" NUMERIC,
    "Other Operating Expenses" NUMERIC,
    "Depreciation And Amortization In Income Statement" NUMERIC,
    "Amortization" NUMERIC,
    "Depreciation Income Statement" NUMERIC,
    "Selling General And Administration" NUMERIC,
    "Selling And Marketing Expense" NUMERIC,
    "General And Administrative Expense" NUMERIC,
    "Rent And Landing Fees" NUMERIC,
    "Gross Profit" NUMERIC,
    "Cost Of Revenue" NUMERIC,
    "Total Revenue" NUMERIC,
    "Operating Revenue" NUMERIC,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (stock_symbol, "Date")
);


CREATE TABLE vq_tbl_balance_sheet (
    id SERIAL PRIMARY KEY,
    stock_symbol TEXT REFERENCES vq_tbl_stock(stock_symbol),
    "Date" DATE,
    "Ordinary Shares Number" NUMERIC,
    "Share Issued" NUMERIC,
    "Total Debt" NUMERIC,
    "Tangible Book Value" NUMERIC,
    "Invested Capital" NUMERIC,
    "Working Capital" NUMERIC,
    "Net Tangible Assets" NUMERIC,
    "Capital Lease Obligations" NUMERIC,
    "Common Stock Equity" NUMERIC,
    "Total Capitalization" NUMERIC,
    "Total Equity Gross Minority Interest" NUMERIC,
    "Minority Interest" NUMERIC,
    "Stockholders Equity" NUMERIC,
    "Other Equity Interest" NUMERIC,
    "Retained Earnings" NUMERIC,
    "Additional Paid In Capital" NUMERIC,
    "Capital Stock" NUMERIC,
    "Common Stock" NUMERIC,
    "Total Liabilities Net Minority Interest" NUMERIC,
    "Total Non Current Liabilities Net Minority Interest" NUMERIC,
    "Other Non Current Liabilities" NUMERIC,
    "Non Current Pension And Other Postretirement Benefit Plans" NUMERIC,
    "Non Current Deferred Revenue" NUMERIC,
    "Non Current Deferred Taxes Liabilities" NUMERIC,
    "Long Term Debt And Capital Lease Obligation" NUMERIC,
    "Long Term Capital Lease Obligation" NUMERIC,
    "Long Term Debt" NUMERIC,
    "Long Term Provisions" NUMERIC,
    "Current Liabilities" NUMERIC,
    "Other Current Liabilities" NUMERIC,
    "Current Debt And Capital Lease Obligation" NUMERIC,
    "Current Capital Lease Obligation" NUMERIC,
    "Current Debt" NUMERIC,
    "Pensionand Other Post Retirement Benefit Plans Current" NUMERIC,
    "Current Provisions" NUMERIC,
    "Payables" NUMERIC,
    "Other Payable" NUMERIC,
    "Dividends Payable" NUMERIC,
    "Total Tax Payable" NUMERIC,
    "Accounts Payable" NUMERIC,
    "Total Assets" NUMERIC,
    "Total Non Current Assets" NUMERIC,
    "Other Non Current Assets" NUMERIC,
    "Non Current Prepaid Assets" NUMERIC,
    "Non Current Deferred Assets" NUMERIC,
    "Non Current Deferred Taxes Assets" NUMERIC,
    "Investmentin Financial Assets" NUMERIC,
    "Available For Sale Securities" NUMERIC,
    "Long Term Equity Investment" NUMERIC,
    "Investmentsin Joint Venturesat Cost" NUMERIC,
    "Investments In Other Ventures Under Equity Method" NUMERIC,
    "Investment Properties" NUMERIC,
    "Goodwill And Other Intangible Assets" NUMERIC,
    "Other Intangible Assets" NUMERIC,
    "Goodwill" NUMERIC,
    "Net PPE" NUMERIC,
    "Accumulated Depreciation" NUMERIC,
    "Gross PPE" NUMERIC,
    "Construction In Progress" NUMERIC,
    "Other Properties" NUMERIC,
    "Machinery Furniture Equipment" NUMERIC,
    "Buildings And Improvements" NUMERIC,
    "Land And Improvements" NUMERIC,
    "Properties" NUMERIC,
    "Current Assets" NUMERIC,
    "Other Current Assets" NUMERIC,
    "Assets Held For Sale Current" NUMERIC,
    "Current Deferred Assets" NUMERIC,
    "Restricted Cash" NUMERIC,
    "Prepaid Assets" NUMERIC,
    "Inventory" NUMERIC,
    "Inventories Adjustments Allowances" NUMERIC,
    "Other Inventories" NUMERIC,
    "Finished Goods" NUMERIC,
    "Work In Process" NUMERIC,
    "Raw Materials" NUMERIC,
    "Other Receivables" NUMERIC,
    "Taxes Receivable" NUMERIC,
    "Accounts Receivable" NUMERIC,
    "Allowance For Doubtful Accounts Receivable" NUMERIC,
    "Gross Accounts Receivable" NUMERIC,
    "Cash Cash Equivalents And Short Term Investments" NUMERIC,
    "Other Short Term Investments" NUMERIC,
    "Cash And Cash Equivalents" NUMERIC,
    "Cash Equivalents" NUMERIC,
    "Cash Financial" NUMERIC,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (stock_symbol, "Date")
);


CREATE TABLE vq_tbl_income_statement (
    id SERIAL PRIMARY KEY,
    stock_symbol TEXT REFERENCES vq_tbl_stock(stock_symbol),
    "Date" DATE,
    "Tax Effect Of Unusual Items" NUMERIC,
    "Tax Rate For Calcs" NUMERIC,
    "Normalized EBITDA" NUMERIC,
    "Total Unusual Items" NUMERIC,
    "Total Unusual Items Excluding Goodwill" NUMERIC,
    "Net Income From Continuing Operation Net Minority Interest" NUMERIC,
    "Reconciled Depreciation" NUMERIC,
    "Reconciled Cost Of Revenue" NUMERIC,
    "EBITDA" NUMERIC,
    "EBIT" NUMERIC,
    "Net Interest Income" NUMERIC,
    "Interest Expense" NUMERIC,
    "Interest Income" NUMERIC,
    "Normalized Income" NUMERIC,
    "Net Income From Continuing And Discontinued Operation" NUMERIC,
    "Total Expenses" NUMERIC,
    "Rent Expense Supplemental" NUMERIC,
    "Diluted Average Shares" NUMERIC,
    "Basic Average Shares" NUMERIC,
    "Diluted EPS" NUMERIC,
    "Basic EPS" NUMERIC,
    "Diluted NI Availto Com Stockholders" NUMERIC,
    "Net Income Common Stockholders" NUMERIC,
    "Otherunder Preferred Stock Dividend" NUMERIC,
    "Net Income" NUMERIC,
    "Minority Interests" NUMERIC,
    "Net Income Including Noncontrolling Interests" NUMERIC,
    "Net Income Discontinuous Operations" NUMERIC,
    "Net Income Continuous Operations" NUMERIC,
    "Tax Provision" NUMERIC,
    "Pretax Income" NUMERIC,
    "Other Non Operating Income Expenses" NUMERIC,
    "Special Income Charges" NUMERIC,
    "Other Special Charges" NUMERIC,
    "Write Off" NUMERIC,
    "Impairment Of Capital Assets" NUMERIC,
    "Net Non Operating Interest Income Expense" NUMERIC,
    "Total Other Finance Cost" NUMERIC,
    "Interest Expense Non Operating" NUMERIC,
    "Interest Income Non Operating" NUMERIC,
    "Operating Income" NUMERIC,
    "Operating Expense" NUMERIC,
    "Other Operating Expenses" NUMERIC,
    "Depreciation And Amortization In Income Statement" NUMERIC,
    "Amortization" NUMERIC,
    "Depreciation Income Statement" NUMERIC,
    "Selling General And Administration" NUMERIC,
    "Selling And Marketing Expense" NUMERIC,
    "General And Administrative Expense" NUMERIC,
    "Rent And Landing Fees" NUMERIC,
    "Gross Profit" NUMERIC,
    "Cost Of Revenue" NUMERIC,
    "Total Revenue" NUMERIC,
    "Operating Revenue" NUMERIC,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (stock_symbol, "Date")
);


CREATE TABLE vq_tbl_cash_flow_statement (
    id SERIAL PRIMARY KEY,
    stock_symbol TEXT REFERENCES vq_tbl_stock(stock_symbol),
    "Date" DATE,
    "Free Cash Flow" NUMERIC,
    "Repayment Of Debt" NUMERIC,
    "Capital Expenditure" NUMERIC,
    "End Cash Position" NUMERIC,
    "Beginning Cash Position" NUMERIC,
    "Effect Of Exchange Rate Changes" NUMERIC,
    "Changes In Cash" NUMERIC,
    "Financing Cash Flow" NUMERIC,
    "Interest Paid Cff" NUMERIC,
    "Cash Dividends Paid" NUMERIC,
    "Net Issuance Payments Of Debt" NUMERIC,
    "Net Short Term Debt Issuance" NUMERIC,
    "Short Term Debt Payments" NUMERIC,
    "Investing Cash Flow" NUMERIC,
    "Net Other Investing Changes" NUMERIC,
    "Interest Received Cfi" NUMERIC,
    "Dividends Received Cfi" NUMERIC,
    "Net Investment Purchase And Sale" NUMERIC,
    "Sale Of Investment" NUMERIC,
    "Purchase Of Investment" NUMERIC,
    "Net Business Purchase And Sale" NUMERIC,
    "Purchase Of Business" NUMERIC,
    "Net Intangibles Purchase And Sale" NUMERIC,
    "Purchase Of Intangibles" NUMERIC,
    "Net PPE Purchase And Sale" NUMERIC,
    "Sale Of PPE" NUMERIC,
    "Purchase Of PPE" NUMERIC,
    "Operating Cash Flow" NUMERIC,
    "Taxes Refund Paid" NUMERIC,
    "Change In Working Capital" NUMERIC,
    "Change In Other Current Liabilities" NUMERIC,
    "Change In Other Current Assets" NUMERIC,
    "Change In Payable" NUMERIC,
    "Change In Inventory" NUMERIC,
    "Change In Receivables" NUMERIC,
    "Other Non Cash Items" NUMERIC,
    "Provisionand Write Offof Assets" NUMERIC,
    "Deferred Tax" NUMERIC,
    "Depreciation And Amortization" NUMERIC,
    "Amortization Cash Flow" NUMERIC,
    "Depreciation" NUMERIC,
    "Gain Loss On Investment Securities" NUMERIC,
    "Gain Loss On Sale Of PPE" NUMERIC,
    "Net Income From Continuing Operations" NUMERIC,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (stock_symbol, "Date")
);


CREATE TABLE vq_tbl_daily_price_history (
    id SERIAL PRIMARY KEY,
    stock_symbol TEXT REFERENCES vq_tbl_stock(stock_symbol),
    "Date" DATE,
    "Open" NUMERIC,
    "High" NUMERIC,
    "Low" NUMERIC,
    "Close" NUMERIC,
    "Volume" NUMERIC,
    "Dividends" NUMERIC,
    "Stock Splits" NUMERIC,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE vq_tbl_monthly_price_history (
    id SERIAL PRIMARY KEY,
    stock_symbol TEXT REFERENCES vq_tbl_stock(stock_symbol),
    "Date" DATE,
    "Adjusted_Monthly_Close_Price" NUMERIC,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE vq_tbl_intrinsic_pe_ratio (
    id SERIAL PRIMARY KEY,
    stock_symbol TEXT REFERENCES vq_tbl_stock(stock_symbol),
    "Date" DATE,
    "financial_year" NUMERIC,
    "Avg_Price" NUMERIC,
    "EPS" NUMERIC,
    "PE_Ratio" NUMERIC,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
